/*
 * Build the static Odds-only team-label normalization table from CFBD /teams.
 * This deliberately does NOT use buildCfbdTeamsUrl(): that FBS-only endpoint
 * remains the canonical team-catalog boundary.
 *
 * Run against CFBD: npx tsx scripts/fetch-cfbd-odds-team-mascots.ts
 * Rebuild from a saved payload without a provider call:
 *   npx tsx scripts/fetch-cfbd-odds-team-mascots.ts --input /path/to/teams.json
 */

import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import dotenv from 'dotenv';

const root = process.cwd();
const envLocal = path.join(root, '.env.local');
if (fs.existsSync(envLocal)) {
  dotenv.config({ path: envLocal });
} else {
  dotenv.config();
}

type CfbdTeamRow = {
  school?: string | null;
  mascot?: string | null;
  abbreviation?: string | null;
  alternateNames?: string[] | null;
  classification?: string | null;
};

type MascotRow = readonly [
  school: string,
  mascot: string,
  classification: string | null,
  alternateNames: readonly string[],
];

function requiredEnv(name: string): string {
  const value = process.env[name];
  if (!value?.trim()) throw new Error(`Missing env var ${name}. Add it to .env.local or .env`);
  return value.trim();
}

function inputPath(argv: string[]): string | null {
  const index = argv.indexOf('--input');
  if (index === -1) return null;
  const value = argv[index + 1]?.trim();
  if (!value) throw new Error('--input requires a JSON file path');
  return path.resolve(root, value);
}

async function loadRows(input: string | null): Promise<CfbdTeamRow[]> {
  if (input) {
    const parsed = JSON.parse(fs.readFileSync(input, 'utf8')) as unknown;
    if (!Array.isArray(parsed)) throw new Error('--input payload must be an array');
    return parsed as CfbdTeamRow[];
  }

  const response = await fetch('https://api.collegefootballdata.com/teams', {
    headers: {
      Authorization: `Bearer ${requiredEnv('CFBD_API_KEY')}`,
      Accept: 'application/json',
    },
  });
  if (!response.ok) {
    const body = await response.text().catch(() => '');
    throw new Error(`CFBD all-division teams fetch failed: ${response.status} ${body}`);
  }
  const parsed = (await response.json()) as unknown;
  if (!Array.isArray(parsed)) throw new Error('CFBD all-division teams payload must be an array');
  return parsed as CfbdTeamRow[];
}

function normalizedRows(rows: CfbdTeamRow[]): MascotRow[] {
  const bySchoolAndMascot = new Map<
    string,
    { school: string; mascot: string; classification: string | null; alternateNames: Set<string> }
  >();
  for (const row of rows) {
    const school = row.school?.trim();
    const mascot = row.mascot?.trim();
    if (!school || !mascot) continue;
    const key = `${school.toLowerCase()}\u0000${mascot.toLowerCase()}`;
    const classification = row.classification?.trim().toLowerCase() || null;
    const existing = bySchoolAndMascot.get(key);
    const item =
      existing ??
      ({ school, mascot, classification, alternateNames: new Set<string>() } satisfies {
        school: string;
        mascot: string;
        classification: string | null;
        alternateNames: Set<string>;
      });
    if (item.classification === null) item.classification = classification;
    const alternateNames = [row.abbreviation, ...(row.alternateNames ?? [])]
      .map((value) => value?.trim())
      .filter((value): value is string => Boolean(value) && value !== school);
    for (const alternateName of alternateNames) item.alternateNames.add(alternateName);
    bySchoolAndMascot.set(key, item);
  }
  const result: MascotRow[] = [...bySchoolAndMascot.values()].map((item) => [
    item.school,
    item.mascot,
    item.classification,
    [...item.alternateNames].sort((left, right) => left.localeCompare(right)),
  ]);
  return result.sort(
    (left, right) => left[0].localeCompare(right[0]) || left[1].localeCompare(right[1])
  );
}

function renderArtifact(rows: MascotRow[], generatedAt: string): string {
  const serializedRows = rows.map((row) => `  ${JSON.stringify(row)},`).join('\n');
  return `/* Generated by scripts/fetch-cfbd-odds-team-mascots.ts. */
export const CFBD_ODDS_TEAM_MASCOTS_SOURCE = 'cfbd:/teams' as const;
export const CFBD_ODDS_TEAM_MASCOTS_GENERATED_AT = '${generatedAt}' as const;

// Prettier intentionally leaves one tuple per provider row for a reviewable,
// sub-1,500-line generated artifact.
// prettier-ignore
export const CFBD_ODDS_TEAM_MASCOTS = [
${serializedRows}
] as const;
`;
}

async function main(): Promise<void> {
  const input = inputPath(process.argv.slice(2));
  const providerRows = await loadRows(input);
  const mascotRows = normalizedRows(providerRows);
  const nonFbsMascotRows = mascotRows.filter((row) => row[2] !== 'fbs').length;
  const outFile = path.join(root, 'src', 'data', 'odds-team-mascots.ts');
  fs.writeFileSync(outFile, renderArtifact(mascotRows, new Date().toISOString()), 'utf8');
  console.log(
    `✓ Saved ${mascotRows.length} mascot rows (${nonFbsMascotRows} non-FBS) from ${
      input ? path.relative(root, input) : 'CFBD /teams'
    } to:\n  - ${path.relative(root, outFile)}`
  );
}

main().catch((error) => {
  console.error(
    '✗ fetch-cfbd-odds-team-mascots failed:',
    error instanceof Error ? error.message : error
  );
  process.exit(1);
});
